### ISSUE TITLE
Can not build the skyTPF Server

### ISSUE THREAD

**Issue by marleeng** [ilkcan/skytpf#1]
I installed the hdt-jena library as the README suggests, and I added the following dependencies in the POM :
 	<dependency>
            <groupId>org.rdfhdt</groupId>
            <artifactId>hdt-api</artifactId>
            <version>2.1.1-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>${basedir}/hdt-java/hdt-api/target/hdt-api-2.1.1-SNAPSHOT.jar</systemPath>
        </dependency>

 	<dependency>
            <groupId>org.rdfhdt</groupId>
            <artifactId>hdt-java-cli</artifactId>
            <version>2.1.1-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>${basedir}/hdt-java/hdt-java-cli/target/hdt-java-cli-2.1.1-SNAPSHOT.jar</systemPath>
        </dependency>

 	<dependency>
            <groupId>org.rdfhdt</groupId>
            <artifactId>hdt-java-core</artifactId>
            <version>2.1.1-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>${basedir}/hdt-java/hdt-java-core/target/hdt-java-core-2.1.1-SNAPSHOT.jar</systemPath>
        </dependency>

 	<dependency>
            <groupId>org.rdfhdt</groupId>
            <artifactId>hdt-jena</artifactId>
            <version>2.1.1-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>${basedir}/hdt-java/hdt-jena/target/hdt-jena-2.1.1-SNAPSHOT.jar</systemPath>
        </dependency>

 	<dependency>
            <groupId>org.rdfhdt</groupId>
            <artifactId>hdt-fuseki</artifactId>
            <version>2.1.1-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>${basedir}/hdt-java/hdt-fuseki/target/hdt-fuseki-2.1.1-SNAPSHOT.jar</systemPath>
        </dependency>

However, when I try to build the server, I get errors similar to the following:
[ERROR] skytpf/server/src/main/java/org/linkeddatafragments/datasource/hdt/TripleIDProducingIterator.java: [70,9] incompatible types: possible lossy conversion from long to int

Can you help me to run this tool?

**Comment by ilkcan** [comment]
It seems like they changed the return type of this function to long. I will make the necessary changes in the earliest possibility (~2 weeks). 

This is the only error you get, right?

**Comment by marleeng** [comment]
Thanks!. Until now, it's the only error. I've only tried to build the server. I haven't tried to build the client yet.

**Comment by ilkcan** [comment]
Hi @marleeng ,

I fixed the issue in the latest commit. As I suspected, they changed the type of the IDs in hdt-java library from integer to long. Can you please try again and let me know if the issue is fixed?

Best,
-ilkcan
